version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
      - MYSQL_PASSWORD=user
      - MYSQL_USER=user

  user-service:
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/userdb
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8090
      SPRING_FLYWAY_URL: jdbc:mysql://mysqldb:3306/userdb
      FLYWAY_USER: user
      FLYWAY_PASSWORD: user
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - config-server
      - eureka-server

  config-server:
    container_name: config-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"