server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    create-schemas: true
    locations: classpath:db/migration
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
    user: root
    password: root
  config:
    import: optional:configserver:http://config-server:8090
